### PR TITLE
Added shortcode helper

### PR DESCRIPTION
**Pull request by srdjan-jcc**
Checks if there are unregistered shortcodes on page/site.
Enable shortcode helper debug data, browse pages that use shortcodes,
check output on pages and overview on settings screen.

https://onthegosystems.myjetbrains.com/youtrack/issue/mt-66

### CODE REVIEW

**Comment by dgwatkins** [comment]
@srdjan-jcc I tried the branch on a site I'm working on and I get an error:

```
Fatal error: Uncaught Error: Call to undefined function icl_xml2array() in wp-content/plugins/sitepress-multilingual-cms/classes/xml-config/class-wpml-config.php:215 
Stack trace: 
#0 wp-content/plugins/sitepress-multilingual-cms/classes/xml-config/class-wpml-config.php(143): WPML_Config::check_on_config_file('WPBakery Page B...') 
#1 wp-content/plugins/sitepress-multilingual-cms/classes/xml-config/class-wpml-config.php(38): WPML_Config::load_plugins_wpml_config() 
#2 wp-content/plugins/multilingual-tools/inc/class-mltools-shortcode-wpml-config-parser.php(80): WPML_Config::load_config_run() 
#3 wp-content/plugins/multilingual-tools/inc/wpml-compatibility-test-tools.functions.php(457): MLTools_Shortcode_WPML_Config_Parser::get_config() 
#4 wp-content/plugins/multilingual-tools/inc/wpml-compatibility-test-tools.functions.php(446) in wp-content/plugins/sitepress-multilingual-cms/classes/xml-config/class-wpml-config.php on line 215
```

You can see it in the footer: http://panarea.compatibility.wpml.org/

**Comment by dgwatkins** [comment]
@vukvukovich Can you create the develop branch again? then we can rebase this

**Comment by srdjan-jcc** [comment]
@dgwatkins Looks like there is an issue with dependencies on frontend.
Same call works fine in admin area.
Checking...

**Comment by srdjan-jcc** [comment]
@dgwatkins Should be fixed now.
Added few other minor fixes.

**Review by dgwatkins — APPROVED** [review]
Works now, very interesting work.
Should save us lots of time.
Well done.

**Comment by dgwatkins** [comment]
We still need to create `develop` branch and rebase, I think.
@vukvukovich

**Comment by srdjan-jcc** [comment]
Added displaying captured values on demand.

**Pull request merged**
